apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: javi-collector
  namespace: apm
spec:
  # 롤링 업데이트 / 노드 드레인 시에도 최소 1개 Pod 보장
  minAvailable: 1
  selector:
    matchLabels:
      app: javi-collector
