apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collector-data
  namespace: apm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  # storageClassName: standard  # 클러스터 기본 StorageClass 사용
