apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: javi-collector
  namespace: apm
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: javi-collector
  endpoints:
    - port: http-otlp
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - apm
