apiVersion: v1
kind: ServiceAccount
metadata:
  name: javi-collector
  namespace: apm
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: javi-forecast
  namespace: apm
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: javi-dashboard
  namespace: apm
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: javi-config-server
  namespace: apm
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama
  namespace: apm
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qdrant
  namespace: apm
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse
  namespace: apm
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-backup
  namespace: apm
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: apm
automountServiceAccountToken: false
