apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: javi-forecast
  namespace: apm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: javi-forecast
  minReplicaCount: 2
  maxReplicaCount: 8
  cooldownPeriod: 300
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: apm-kafka-kafka-bootstrap:9092
        consumerGroup: javi-forecast
        topic: spans.all
        lagThreshold: "100"
        offsetResetPolicy: latest
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 120
          policies:
            - type: Pods
              value: 2
              periodSeconds: 120
        scaleDown:
          stabilizationWindowSeconds: 600
          policies:
            - type: Pods
              value: 1
              periodSeconds: 300
