apiVersion: v1
kind: ResourceQuota
metadata:
  name: apm-quota
  namespace: apm
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "24Gi"
    limits.cpu: "20"
    limits.memory: "48Gi"
    pods: "60"
    services: "20"
    persistentvolumeclaims: "20"
    secrets: "40"
    configmaps: "40"
